### ISSUE TITLE
1.0.0 jar in 1.0.1 release fails to start on mc 1.17.1

### ISSUE THREAD

**Issue by ghost** [CodedSakura/FabricNoMobGrief#3]
1.01 release on github and modrinth both contain fabric-no-mob-grief-1.0.0.jar that crashes on launch with mc 1.17.1.

I used fabric-no-creeper-grief-1.0.1-dev.jar from github instead and it launched successfully.

```
Failed to launch!
Could not find required mod: fabric-no-mob-grief requires {minecraft @ [~1.16.2]}
Creating Empty clause?
```

```
[11:55:39] [main/INFO]: Loading for game Minecraft 1.17.1
[11:55:39] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: fabric-no-mob-grief requires {minecraft @ [~1.16.2]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:198) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:195) ~[fabric-loader-0.11.6.jar:?]
	... 5 more
```

**Comment by CodedSakura** [comment]
ah, i put the wrong jar on modrinth...

**Comment by CodedSakura** [comment]
(actually, i'm quite confused as to how the 1.0.0 jar on GH worked while the same jar on Modrinth didn't.... it shouldn't have worked on 1.17 either way)

**Comment by ghost** [comment]
Neither the 1.0.0 jar from github or modrinth worked. It was the 1.0.1-dev.jar from github that loaded without a crash.

Thanks, tested the new release from modrinth and everything works well.

**Comment by CodedSakura** [comment]
ah, misread that, the -dev working does make sense
